### ISSUE TITLE
Chipmunk on N64! Nice!

### ISSUE THREAD

**Issue by slembcke** [Davermouse/ggj24mml64#1]
I was looking for other retro-dev projects made for the GGJ this year and came across your project. This is the first N64 game I've seen using Chipmunk2D. Neat!

My team made (yet another) NES game. :)
https://globalgamejam.org/games/2024/slapstick-nes-9

**Comment by Davermouse** [comment]
Cheers - I saw Chipmunk2D mentioned on the N64Brew Discord and thought it was worth a go, and after a bit of bodging it kinda works. At some point I want to publish a little starter project for it, this ended up kinda a horrible mess by the end...

Nice work with yours - NES looks like a whole other level of difficulty.

**Comment by slembcke** [comment]
This is actually the 5th time I've made a NES game for the GGJ. It's not bad if you limit yourself. (ex: use static tile sheets, limit scrolling to the 2 screens that the GPU provides, keep math as simple as possible, use global variables liberally, etc)

I'm actually a little disappointed how few retro entries there were this year. I could only find our NES game, a Genesis game (made by someone I knew), a PSP game, and yours. I sort of figured with the Unity fallout that people would be more willing to try crazy things. Haha. Oh well.

Anyway, have a good one!
